name: Deploy to Firebase on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: 16
      - run: |
          echo "${ENV}" | tr ';' '\n' > packages/app/.env
          yarn && yarn workspaces run build
      - name: Configure SA file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DAILY_CONFIDENCE_POLL }}' > $HOME/gcloud.json
      - name: Deploy to Firebase
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && yarn firebase --non-interactive deploy